version: '3.3'
services:
    portainer-ce:
        image: portainer/portainer-ce:latest
        container_name: ${COMPOSE_PROJECT_NAME}
        restart: unless-stopped
        ports:
            - '${PORTAINER_HTTP_PORT:-9000}:9000'
        volumes:
            - './data:/data'
            - '/var/run/docker.sock:/var/run/docker.sock'
